openapi: 3.0.3
info:
  title: API de la Orden Jedi
  description: |
    API RESTful para el registro de Jedis en la Galaxia. 
    Permite el alta, modificación, consulta y eliminación de maestros, 
    padawans y consejeros.
  version: 1.0.0
  contact:
    name: Equipo de Desarrollo Jedi
    email: alberto.aguilar@tec.mx
servers:
  - url: https://api.consejo.galactico/v1
    description: Entorno de Producción
  - url: http://localhost:8080/v1
    description: Entorno de Desarrollo Local
security:
  - BearerAuth: []
tags:
  - name: Jedis
    description: Operaciones de registro y perfil de Jedis
  - name: Rangos
    description: Gestión de los rangos de la Orden

paths:
  /jedis:
    get:
      tags:
        - Jedis
      summary: Obtener lista de Jedis
      operationId: getJedis
      parameters:
        - name: rango
          in: query
          description: Filtra por el rango del Jedi (ej. Maestro, Padawan)
          required: false
          schema:
            type: string
        - name: pagina
          in: query
          description: Número de página para paginación
          required: false
          schema:
            type: integer
            default: 1
      responses:
        '200':
          description: Lista de Jedis retornada con éxito.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Jedi'
        '401':
          $ref: '#/components/responses/UnauthorizedError'

    post:
      tags:
        - Jedis
      summary: Registrar un nuevo Jedi
      operationId: createJedi
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/JediCreacion'
      responses:
        '201':
          description: Jedi creado satisfactoriamente.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Jedi'
        '400':
          $ref: '#/components/responses/BadRequestError'

  /jedis/{jediId}:
    parameters:
      - name: jediId
        in: path
        description: ID único del Jedi.
        required: true
        schema:
          type: integer
          format: int64
    get:
      tags:
        - Jedis
      summary: Consultar los detalles de un Jedi por ID
      operationId: getJediById
      responses:
        '200':
          description: Detalles del Jedi.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Jedi'
        '404':
          $ref: '#/components/responses/NotFoundError'

    put:
      tags:
        - Jedis
      summary: Modificar completamente los datos de un Jedi
      operationId: updateJedi
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/JediCreacion'
      responses:
        '200':
          description: Jedi modificado con éxito.
        '404':
          $ref: '#/components/responses/NotFoundError'

    delete:
      tags:
        - Jedis
      summary: Dar de baja (borrar) un Jedi
      operationId: deleteJedi
      responses:
        '204':
          description: Jedi eliminado con éxito (Sin Contenido).
        '404':
          $ref: '#/components/responses/NotFoundError'

  /jedis/{jediId}/rango:
    patch:
      tags:
        - Rangos
      summary: Modificar solo el rango de un Jedi
      operationId: patchJediRank
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nuevoRango:
                  type: string
                  description: Nuevo rango asignado (ej. Caballero, Maestro).
      responses:
        '200':
          description: Rango del Jedi actualizado.
        '404':
          $ref: '#/components/responses/NotFoundError'
        '403':
          description: Prohibido. El usuario no es un Maestro del Consejo.

  /rangos:
    get:
      tags:
        - Rangos
      summary: Obtener la lista de rangos disponibles
      operationId: getRangos
      responses:
        '200':
          description: Lista de rangos de la Orden Jedi.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Rango'

components:
  schemas:
    Jedi:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: ID único del Jedi.
          example: 42
        nombre:
          type: string
          description: Nombre completo del Jedi.
          example: Obi-Wan Kenobi
        rango:
          type: string
          description: Nivel dentro de la Orden.
          example: Maestro
        especie:
          type: string
          description: Especie a la que pertenece el Jedi.
          example: Humano
        padawanId:
          type: integer
          format: int64
          nullable: true
          description: ID del Padawan a cargo (si aplica).
          example: 99
      required:
        - nombre
        - rango
        - especie

    JediCreacion:
      type: object
      description: Modelo para la creación o actualización completa de un Jedi.
      allOf:
        - $ref: '#/components/schemas/Jedi'
        - properties:
            midiclorianos:
              type: integer
              description: Nivel de midiclorianos (dato sensible/solo al crear).
              readOnly: true
        - required:
            - midiclorianos

    Rango:
      type: object
      properties:
        nombre:
          type: string
          example: Caballero
        minJedis:
          type: integer
          description: Número mínimo de Jedis requeridos para este rango.

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Autenticación mediante un token JWT.

  responses:
    NotFoundError:
      description: Recurso no encontrado. El ID proporcionado no existe.
      content:
        application/json:
          schema:
            type: object
            properties:
              codigo:
                type: string
                example: JEDI_404
              mensaje:
                type: string
                example: No se encontró ningún Jedi con el ID especificado.
    BadRequestError:
      description: Solicitud incorrecta. Faltan campos requeridos o el formato es inválido.
    UnauthorizedError:
      description: Acceso no autorizado. Falta el token de autenticación o es inválido.